name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7328
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.dsi-config
      ref: feature/DSI-7328

trigger:
  branches:
    include:
    - feature/*
    - main
    - release/*

pr:
  branches:
    include:
    - main

parameters:
- name: location
  type: object
  displayName: 'Deployment locations (- westeurope & - northeurope)'
  default:
    - westeurope
    - northeurope
- name: shaUse
  type: boolean
  displayName: "Use Self Host agent"
  default: true
- name: slotDeploy
  type: boolean
  displayName: "Slot Deployment"
  default: true
- name: InfrDeploy
  type: boolean
  displayName: 'Infrastrucure Deployment only'
  default: false
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false
- name: gitCheck
  type: boolean
  displayName: 'Bypass Git Check in Test'
  default: false

variables:
- group: dsi-global
- name: applicationShortName
  value: 'svc'
- name: applicationFullName
  value: 'services'
- name: numberOfWorkers
  value: 1
- name: tran
  ${{ if eq(parameters.tran, 'true') }}:
    value: true
  ${{ else }}:
    value: true
- name: dev
  ${{ if or(eq(parameters.dev, 'true'), contains(variables['Build.SourceBranch'],'feature')) }}:
    value: false
  ${{ else }}:
    value: false
- name: test
  ${{ if or(eq(parameters.test, 'true'), contains(variables['Build.SourceBranch'],'feature')) }}:
    value: false
  ${{ else }}:
    value: false
- name: pp
  ${{ if and(or(eq(parameters.pp, 'true'), contains(variables['Build.SourceBranch'],'main')), not(contains(variables['Build.SourceVersionMessage'],'Upgrade to version'))) }}:
    value: true
  ${{ else }}:
    value: false
- name: pr
  ${{ if or(eq(parameters.pr, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false

stages:

# Code Scans & Build the artifact for deployment
- stage: scanBuildApp
  displayName: "Scan tools & Build"
  jobs:

  - template:  pipeline/scanTools.yml@devopsTemplates
    parameters:
      npmInstCmd: 'install --force --json --no-package-lock'
      AppDeploy: ${{ not(parameters.InfrDeploy) }}

  - ${{ if not(eq(parameters.InfrDeploy, 'true')) }}:
    - template: pipeline/buildAzureAppServices.yml@devopsTemplates
      parameters:
        applicationName: ${{variables.applicationFullName}}
        custRegAuth: $(custRegAuth)
        ContRegServers:
          - ${{ if or(or(eq(variables.tran, 'true'), eq(variables.dev, 'true')), and(contains(variables['Build.SourceVersionMessage'],'Merge pull request'), contains(variables['Build.SourceVersionMessage'],'feature'))) }}:
            - $(platformGlobalIdentifier)d03$(platformGlobalName)shdcr.azurecr.io
          - ${{ if or(eq(variables.test, 'true'), eq(variables.pp, 'true')) }}:
            - $(platformGlobalIdentifier)t02$(platformGlobalName)shdcr.azurecr.io
          - ${{ if or(eq(variables.pr, 'true'), and(contains(variables['Build.SourceVersionMessage'],'Merge pull request'), contains(variables['Build.SourceVersionMessage'],'release'))) }}:
            - $(platformGlobalIdentifier)p01$(platformGlobalName)shdcr.azurecr.io
        nodeVersionSpec: '18.17.0'


- ${{ each location in parameters.location }}:
  - ${{ each var in variables }}:
    - ${{ if in(var.key, 'tran','dev','test','pp','pr') }}:
      - ${{ if eq(var.value, 'true') }}:
        - ${{ if or(and(in(var.key, 'tran','pp','pr'),eq(location, 'northeurope')),and(in(var.key, 'tran','dev','test','pp','pr'),eq(location, 'westeurope'))) }}:
          - stage: Deployment_${{var.key}}_${{location}}
            displayName: "Deployment [${{var.key}}] ${{location}}"
            ${{ if eq(location,'westeurope') }}:
              dependsOn: 
              - scanBuildApp
              condition: in(dependencies.scanBuildApp.result, 'Succeeded', 'Skipped')
            ${{ if eq(location,'northeurope') }}:
              dependsOn: 
              - scanBuildApp
              condition: in(dependencies.scanBuildApp.result, 'Succeeded', 'Skipped')
            variables:
            - name: environmentId
              ${{ if eq(var.key, 'tran') }}:
                value: d03
              ${{ if eq(var.key, 'dev') }}:
                value: d01
              ${{ if eq(var.key, 'test') }}:
                value: t01
              ${{ if eq(var.key, 'pp') }}:
                value: t02
              ${{ if eq(var.key, 'pr') }}:
                value: p01
            jobs:
            - template: pipeline/deployAzureAppServices.yml@devopsTemplates
              parameters:
                ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                  serviceConnection: $(devServiceConnection)
                ${{ elseif eq(var.key, 'pr') }}:
                  serviceConnection: $(prodServiceConnection)
                ${{ else }}:
                  serviceConnection: $(testServiceConnection)
                environmentName: ${{var.key}}
                applicationShortName: ${{variables.applicationShortName}}
                applicationFullName: ${{variables.applicationFullName}}
                releaseArtifactName: ${{variables.applicationShortName}}-${{var.key}}-$(Build.BuildId)-release
                InfrDeploy: ${{parameters.InfrDeploy}}
                deploymentLocation: ${{location}}
                gitCheck: ${{parameters.gitCheck}}
                tier: presentation
                tierPlan: prestier-g3
                shaUse: true
                slotDeploy: ${{parameters.slotDeploy}}
                appRepoName: ${{variables.applicationFullName}}
          
          - ${{ if and(eq(var.key, 'pr'),eq(location, 'westeurope')) }}:
            - stage: branchPrTag
              displayName: "GitHub PR & Release Branch Tag"
              dependsOn: 
              - Deployment_${{var.key}}_${{location}}
              jobs:
              - template:  pipeline/tagCreation.yml@devopsTemplates
                parameters:
                  applicationName: ${{variables.applicationFullName}}